### ISSUE TITLE
Release under benchmarks-game license

### ISSUE THREAD

**Issue by non-Jedi** [JuliaPerf/BenchmarksGame.jl#39]
Benchmarks contributed to the benchmarks game website must be released under the [benchmarks-game license](https://salsa.debian.org/benchmarksgame-team/benchmarksgame/blob/master/LICENSE.md) (revised BSD). This repo currently has no license other than those benchmarks derived from those in Base. Could all the contributors please comment below affirming they release their changes under the linked license?

- @KristofferC 
- @SimonDanisch 
- @maltezfaria 
- @hycakir 
- @tkoolen 
- @jrevels 
- @PallHaraldsson 

Thanks

**Comment by jrevels** [comment]
ref https://github.com/JuliaPerf/BenchmarksGame.jl/pull/31, not sure if I should even count as a contributor 😛but fine with the license regardless.

**Comment by SimonDanisch** [comment]
Sure :)

**Comment by KristofferC** [comment]
:+1:

**Comment by maltezfaria** [comment]
👍

**Comment by tkoolen** [comment]
👍

**Comment by hycakir** [comment]
Sure!

**Comment by KristofferC** [comment]
PallHaraldson's contribution is limited to https://github.com/JuliaPerf/BenchmarksGame.jl/commit/6b55550b2617091e213ad9c7e6c1da1a69ac3389 which is negligible so should be fine to relicense now.
